STYLE_PROMPT_MAP = {
    "Photorealistic": "A jaw droppingly realistic, photorealistic logo. No cartoons. Museum grade realism.",
    "Corporate": "A sleek modern corporate photorealistic logo. Polished and professional.",
    "Cartoon": "A wildly colorful cartoon style logo with exaggerated features.",
    "8bit": "A retro 8 bit pixel art logo, arcade cabinet era.",
    "Pixel Sprite": "A 16 bit pixel sprite logo, SNES era.",
    "90sNFO": "ASCII ANSI art logo in monospaced text, 90s warez BBS vibe.",
    "Hacker Art": "Dark neon cyberpunk glitch art logo, terminal green and neon accents.",
    "Minimal": "Minimalist logo with crisp lines, max three colors, heavy whitespace.",
    "Vector": "Vector illustration logo built from clean geometric shapes.",
    "80s Movies": "Over the top 1980s movie poster energy. Neon, bold, cinematic.",
    "Max Headroom": "1980s cyber glitch VHS scanline energy. High contrast neon.",
    "HOWARD THE DUCK": "Absurd Howard the Duck themed logo everywhere.",
    "Darkwing Duck": "Heroic Darkwing Duck vibe with cape and gadgets.",
    "Gremlin Themed": "Mischievous Gremlins energy with neon chaos.",
    "SecKC": "Kansas City hacker pride hexagon badge, DIY makerspace energy.",
    "Shinobi": "Futuristic blue cyber ninja logo, angular eyes, neon gradients.",
    "Matrix": "1999 matrix green digital rain and grid aesthetics.",
    "DOOM": "Brutal metallic DOOM 1993 style, heavy gradients and demons.",
    "Larry and the Lounge Lizards": "1980s sleaze neon casino vibe, kitsch and disco.",
    "Whatever": "Unhinged unpredictable chaotic creativity.",
    "Choose Your Own Adventure": "Fully user driven custom concept per input.",
    "Vaporwave": "Pastel vaporwave mall nostalgia, VHS glitches and palm trees.",
    "Pirate Hacker": "Swashbuckling pirate fused with hacker imagery and WiFi Jolly Roger.",
    "Cat Meme": "Internet cat meme chaos with keyboards and lasers.",
    "Retro Sci Fi Paperback": "1970s paperback cover style, ray guns and starfields.",
}

STYLE_OPTIONS = [
    "8bit",
    "Hacker Art",
    "90sNFO",
    "Pixel Sprite",
    "Photorealistic",
    "Corporate",
    "Cartoon",
    "Minimal",
    "Vector",
    "80s Movies",
    "Max Headroom",
    "HOWARD THE DUCK",
    "Gremlin Themed",
    "SecKC",
    "Shinobi",
    "Darkwing Duck",
    "Matrix",
    "DOOM",
    "Larry and the Lounge Lizards",
    "Whatever",
    "Choose Your Own Adventure",
    "Vaporwave",
    "Pirate Hacker",
    "Cat Meme",
    "Retro Sci Fi Paperback",
]


def style_choices():
    return STYLE_OPTIONS
